### ISSUE TITLE
DAOn korjailua

### ISSUE THREAD

**Issue by riihikallio** [VirtualAkseli/Lukuvinkkikirjasto-Napsa#18]
Tällä hetkellä DAO heittää poikkeuksia. Oikeaoppisesti FileNotFound ym. pitäisi kapseloida DAOn sisälle. Nyt käyttöliittymässä tarvitsee varautua try-catch -rakenteilla. Entä jos DAO muutetaan tietokantapohjaiseksi? Pitäisikö varautua toisiin virheisiin?

Käytännön ongelma syntyy tällä hetkellä testeistä. Mockito luo mockin, joka saattaa heittää poikkeuksia. Niihin pitäisi varautua jokaisessa testissä, mistä syntyy ilmeisesti ongelma. En ainakaan saanut yhtään testiä toimimaan kun Mockiton **when** oli try-catchin sisällä.

Toinen DAOssa refaktorointia vaativa on tiedostonimi. Sen pitäisi olla DAOssa eikä käyttöliittymässä. Taas: mitä tiedostonimi tarkoittaisi SQL-kannan yhteydessä. Joku oli lisännyt sille vieläpä getterin käyttöliittymään :)

**Comment by VirtualAkseli** [comment]
Korjattu pullarissa 20#
